version: '3.4'

services:
    basketmicroservice_basketdb:
        container_name: basketmicroservice_basketdb
        restart: always
        ports:
            - "6379:6379" #Redis officially exposing on that port

    basketmicroservice_basket.api:
        container_name: basketmicroservice_basketapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:Redis=basketmicroservice_basketdb:6379" #should match the container name include Redis
        depends_on:
            - basketmicroservice_basketdb
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "9000:80"